
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'Banner': typeof import("../components/Banner.vue")['default']
    'BaseDrawer': typeof import("../components/Base/BaseDrawer.vue")['default']
    'BaseInput': typeof import("../components/Base/BaseInput.vue")['default']
    'BaseModal': typeof import("../components/Base/BaseModal.vue")['default']
    'BaseButton': typeof import("../components/Base/Button.vue")['default']
    'BaseHeading': typeof import("../components/Base/Heading.vue")['default']
    'BaseParagraph': typeof import("../components/Base/Paragraph.vue")['default']
    'BaseSeperator': typeof import("../components/Base/Seperator.vue")['default']
    'BaseSubHeading': typeof import("../components/Base/SubHeading.vue")['default']
    'BaseTextarea': typeof import("../components/Base/Textarea.vue")['default']
    'BenefitsOfMoxie': typeof import("../components/BenefitsOfMoxie.vue")['default']
    'Branding': typeof import("../components/Branding.vue")['default']
    'Categories': typeof import("../components/Categories.vue")['default']
    'ClientReview': typeof import("../components/ClientReview.vue")['default']
    'Coaching': typeof import("../components/Coaching.vue")['default']
    'Contact': typeof import("../components/Contact.vue")['default']
    'CookieConsentModal': typeof import("../components/CookieConsentModal.vue")['default']
    'CoursesInfo': typeof import("../components/CoursesInfo.vue")['default']
    'Customers': typeof import("../components/Customers.vue")['default']
    'Footer': typeof import("../components/Footer.vue")['default']
    'HeaderAppLogo': typeof import("../components/Header/AppLogo.vue")['default']
    'HeaderDesktop': typeof import("../components/Header/Desktop.vue")['default']
    'HeaderMobile': typeof import("../components/Header/Mobile.vue")['default']
    'Header': typeof import("../components/Header/index.vue")['default']
    'HeroBanner': typeof import("../components/HeroBanner.vue")['default']
    'InfluenceInspire': typeof import("../components/InfluenceInspire.vue")['default']
    'JourneySection': typeof import("../components/JourneySection.vue")['default']
    'MoxieModal': typeof import("../components/MoxieModal.vue")['default']
    'Newslatter': typeof import("../components/Newslatter.vue")['default']
    'ParallaxSection': typeof import("../components/ParallaxSection.vue")['default']
    'Services': typeof import("../components/Services.vue")['default']
    'TrackCard': typeof import("../components/TrackCard.vue")['default']
    'TrackSection': typeof import("../components/TrackSection.vue")['default']
    'TracksMastery': typeof import("../components/TracksMastery.vue")['default']
    'Traning': typeof import("../components/Traning.vue")['default']
    'WorkshopSection': typeof import("../components/WorkshopSection.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyBanner': typeof import("../components/Banner.vue")['default']
    'LazyBaseDrawer': typeof import("../components/Base/BaseDrawer.vue")['default']
    'LazyBaseInput': typeof import("../components/Base/BaseInput.vue")['default']
    'LazyBaseModal': typeof import("../components/Base/BaseModal.vue")['default']
    'LazyBaseButton': typeof import("../components/Base/Button.vue")['default']
    'LazyBaseHeading': typeof import("../components/Base/Heading.vue")['default']
    'LazyBaseParagraph': typeof import("../components/Base/Paragraph.vue")['default']
    'LazyBaseSeperator': typeof import("../components/Base/Seperator.vue")['default']
    'LazyBaseSubHeading': typeof import("../components/Base/SubHeading.vue")['default']
    'LazyBaseTextarea': typeof import("../components/Base/Textarea.vue")['default']
    'LazyBenefitsOfMoxie': typeof import("../components/BenefitsOfMoxie.vue")['default']
    'LazyBranding': typeof import("../components/Branding.vue")['default']
    'LazyCategories': typeof import("../components/Categories.vue")['default']
    'LazyClientReview': typeof import("../components/ClientReview.vue")['default']
    'LazyCoaching': typeof import("../components/Coaching.vue")['default']
    'LazyContact': typeof import("../components/Contact.vue")['default']
    'LazyCookieConsentModal': typeof import("../components/CookieConsentModal.vue")['default']
    'LazyCoursesInfo': typeof import("../components/CoursesInfo.vue")['default']
    'LazyCustomers': typeof import("../components/Customers.vue")['default']
    'LazyFooter': typeof import("../components/Footer.vue")['default']
    'LazyHeaderAppLogo': typeof import("../components/Header/AppLogo.vue")['default']
    'LazyHeaderDesktop': typeof import("../components/Header/Desktop.vue")['default']
    'LazyHeaderMobile': typeof import("../components/Header/Mobile.vue")['default']
    'LazyHeader': typeof import("../components/Header/index.vue")['default']
    'LazyHeroBanner': typeof import("../components/HeroBanner.vue")['default']
    'LazyInfluenceInspire': typeof import("../components/InfluenceInspire.vue")['default']
    'LazyJourneySection': typeof import("../components/JourneySection.vue")['default']
    'LazyMoxieModal': typeof import("../components/MoxieModal.vue")['default']
    'LazyNewslatter': typeof import("../components/Newslatter.vue")['default']
    'LazyParallaxSection': typeof import("../components/ParallaxSection.vue")['default']
    'LazyServices': typeof import("../components/Services.vue")['default']
    'LazyTrackCard': typeof import("../components/TrackCard.vue")['default']
    'LazyTrackSection': typeof import("../components/TrackSection.vue")['default']
    'LazyTracksMastery': typeof import("../components/TracksMastery.vue")['default']
    'LazyTraning': typeof import("../components/Traning.vue")['default']
    'LazyWorkshopSection': typeof import("../components/WorkshopSection.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Banner: typeof import("../components/Banner.vue")['default']
export const BaseDrawer: typeof import("../components/Base/BaseDrawer.vue")['default']
export const BaseInput: typeof import("../components/Base/BaseInput.vue")['default']
export const BaseModal: typeof import("../components/Base/BaseModal.vue")['default']
export const BaseButton: typeof import("../components/Base/Button.vue")['default']
export const BaseHeading: typeof import("../components/Base/Heading.vue")['default']
export const BaseParagraph: typeof import("../components/Base/Paragraph.vue")['default']
export const BaseSeperator: typeof import("../components/Base/Seperator.vue")['default']
export const BaseSubHeading: typeof import("../components/Base/SubHeading.vue")['default']
export const BaseTextarea: typeof import("../components/Base/Textarea.vue")['default']
export const BenefitsOfMoxie: typeof import("../components/BenefitsOfMoxie.vue")['default']
export const Branding: typeof import("../components/Branding.vue")['default']
export const Categories: typeof import("../components/Categories.vue")['default']
export const ClientReview: typeof import("../components/ClientReview.vue")['default']
export const Coaching: typeof import("../components/Coaching.vue")['default']
export const Contact: typeof import("../components/Contact.vue")['default']
export const CookieConsentModal: typeof import("../components/CookieConsentModal.vue")['default']
export const CoursesInfo: typeof import("../components/CoursesInfo.vue")['default']
export const Customers: typeof import("../components/Customers.vue")['default']
export const Footer: typeof import("../components/Footer.vue")['default']
export const HeaderAppLogo: typeof import("../components/Header/AppLogo.vue")['default']
export const HeaderDesktop: typeof import("../components/Header/Desktop.vue")['default']
export const HeaderMobile: typeof import("../components/Header/Mobile.vue")['default']
export const Header: typeof import("../components/Header/index.vue")['default']
export const HeroBanner: typeof import("../components/HeroBanner.vue")['default']
export const InfluenceInspire: typeof import("../components/InfluenceInspire.vue")['default']
export const JourneySection: typeof import("../components/JourneySection.vue")['default']
export const MoxieModal: typeof import("../components/MoxieModal.vue")['default']
export const Newslatter: typeof import("../components/Newslatter.vue")['default']
export const ParallaxSection: typeof import("../components/ParallaxSection.vue")['default']
export const Services: typeof import("../components/Services.vue")['default']
export const TrackCard: typeof import("../components/TrackCard.vue")['default']
export const TrackSection: typeof import("../components/TrackSection.vue")['default']
export const TracksMastery: typeof import("../components/TracksMastery.vue")['default']
export const Traning: typeof import("../components/Traning.vue")['default']
export const WorkshopSection: typeof import("../components/WorkshopSection.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyBanner: typeof import("../components/Banner.vue")['default']
export const LazyBaseDrawer: typeof import("../components/Base/BaseDrawer.vue")['default']
export const LazyBaseInput: typeof import("../components/Base/BaseInput.vue")['default']
export const LazyBaseModal: typeof import("../components/Base/BaseModal.vue")['default']
export const LazyBaseButton: typeof import("../components/Base/Button.vue")['default']
export const LazyBaseHeading: typeof import("../components/Base/Heading.vue")['default']
export const LazyBaseParagraph: typeof import("../components/Base/Paragraph.vue")['default']
export const LazyBaseSeperator: typeof import("../components/Base/Seperator.vue")['default']
export const LazyBaseSubHeading: typeof import("../components/Base/SubHeading.vue")['default']
export const LazyBaseTextarea: typeof import("../components/Base/Textarea.vue")['default']
export const LazyBenefitsOfMoxie: typeof import("../components/BenefitsOfMoxie.vue")['default']
export const LazyBranding: typeof import("../components/Branding.vue")['default']
export const LazyCategories: typeof import("../components/Categories.vue")['default']
export const LazyClientReview: typeof import("../components/ClientReview.vue")['default']
export const LazyCoaching: typeof import("../components/Coaching.vue")['default']
export const LazyContact: typeof import("../components/Contact.vue")['default']
export const LazyCookieConsentModal: typeof import("../components/CookieConsentModal.vue")['default']
export const LazyCoursesInfo: typeof import("../components/CoursesInfo.vue")['default']
export const LazyCustomers: typeof import("../components/Customers.vue")['default']
export const LazyFooter: typeof import("../components/Footer.vue")['default']
export const LazyHeaderAppLogo: typeof import("../components/Header/AppLogo.vue")['default']
export const LazyHeaderDesktop: typeof import("../components/Header/Desktop.vue")['default']
export const LazyHeaderMobile: typeof import("../components/Header/Mobile.vue")['default']
export const LazyHeader: typeof import("../components/Header/index.vue")['default']
export const LazyHeroBanner: typeof import("../components/HeroBanner.vue")['default']
export const LazyInfluenceInspire: typeof import("../components/InfluenceInspire.vue")['default']
export const LazyJourneySection: typeof import("../components/JourneySection.vue")['default']
export const LazyMoxieModal: typeof import("../components/MoxieModal.vue")['default']
export const LazyNewslatter: typeof import("../components/Newslatter.vue")['default']
export const LazyParallaxSection: typeof import("../components/ParallaxSection.vue")['default']
export const LazyServices: typeof import("../components/Services.vue")['default']
export const LazyTrackCard: typeof import("../components/TrackCard.vue")['default']
export const LazyTrackSection: typeof import("../components/TrackSection.vue")['default']
export const LazyTracksMastery: typeof import("../components/TracksMastery.vue")['default']
export const LazyTraning: typeof import("../components/Traning.vue")['default']
export const LazyWorkshopSection: typeof import("../components/WorkshopSection.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
